default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_IP'] %>
  user: <%= ENV['APP_USER_POSTGRES_USER'] %>
  password: <%= ENV['APP_USER_POSTGRES_PASSWORD'] %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: terrier_assessment_development

test:
  <<: *default
  database: terrier_assessment_test

production:
  <<: *default
  database: terrier_assessment_production
  username: terrier_assessment
  password: <%= ENV['TERRIER_ASSESSMENT_DATABASE_PASSWORD'] %>
